// i18n: Sprachsystem (Deutsch + Englisch) für Menü-, Einstellungs- und Pause-Texte.
// Andere Module lesen Strings live über t(); setLang() schaltet ohne Neustart um.

import { Settings } from './settings.js';

export const LANG_NAMES = { de: 'Deutsch', en: 'English' };

// Übersetzungstabelle. Platzhalter {0}, {1} … werden von t(key, ...args) ersetzt.
export const LANGS = {
  de: {
    // Hauptmenü
    'menu.singleplayer': 'Einzelspieler',
    'menu.multiplayer': 'Mehrspieler',
    'menu.settings': 'Einstellungen',
    'menu.quit': 'Beenden',
    'menu.back': '‹ Zurück',
    // Einzelspieler
    'sp.seedPlaceholder': 'Seed (leer = zufällig)',
    'sp.modeSurvival': 'Spielmodus: Überleben',
    'sp.modeCreative': 'Spielmodus: Kreativ',
    'sp.newWorld': 'Neue Welt',
    'sp.continue': 'Welt fortsetzen',
    'sp.delete': 'Welt löschen',
    'sp.deleteConfirm': 'Gespeicherte Welt wirklich löschen?',
    'sp.deleted': 'Welt gelöscht',
    'sp.worldName': 'Weltname (leer = automatisch)',
    'sp.create': 'Neue Welt erstellen',
    'sp.savedWorlds': 'Gespeicherte Welten',
    'sp.noWorlds': 'Noch keine gespeicherten Welten',
    'sp.load': 'Laden',
    'sp.creative': 'Kreativ',
    'sp.survival': 'Überleben',
    // Mehrspieler
    'mp.namePlaceholder': 'Spielername',
    'mp.joinAs': 'Beitreten als:',
    'mp.addrPlaceholder': 'Server-Adresse (leer = dieser Server)',
    'mp.join': 'Mehrspieler beitreten',
    'mp.rejoin': 'Wieder verbinden',
    'mp.defaultName': 'Spieler',
    'mp.prevServers': 'Vorherige Server',
    'mp.noServers': 'Noch keine Server',
    'mp.connect': 'Verbinden',
    'mp.online': 'Online',
    'mp.offline': 'Offline',
    'mp.checking': 'Prüfe …',
    'mp.thisServer': 'Dieser Server',
    // Einstellungen
    'set.title': 'Einstellungen',
    'set.language': 'Sprache',
    'set.renderDistance': 'Sichtweite: {0} Chunks ({1} Blöcke)',
    'set.renderHint': 'Bis {0} Chunks volle Voxel-Details — darüber wird entferntes Gelände ' +
      'vereinfacht dargestellt (Höhenprofil mit Biomfarben). Sehr hohe Werte kosten Leistung. ' +
      'Wirkt sofort, ohne Neustart.',
    'set.creativeSpeed': 'Lauftempo im Kreativmodus: ×{0}',
    'set.done': 'Fertig',
    'set.close': 'Schließen',
    // Abschnitte & neue Optionen
    'set.sec.graphics': 'Grafik',
    'set.sec.performance': 'Leistung',
    'set.sec.controls': 'Steuerung',
    'set.clouds': 'Wolken am Himmel',
    'set.on': 'An',
    'set.off': 'Aus',
    'set.maxFps': 'Bildrate-Grenze: {0}',
    'set.unlimited': 'Unbegrenzt',
    'set.vsync': 'VSync (an Monitor koppeln)',
    'set.vsyncHint': 'VSync koppelt die Bildrate an deinen Monitor (flüssig, kein Tearing). ' +
      'Zum Nutzen der Bildrate-Grenze VSync ausschalten.',
    'set.rebindHint': 'Zum Ändern anklicken und neue Taste drücken · Esc bricht ab',
    'set.rebindWait': '… Taste drücken …',
    'set.resetKeys': 'Steuerung zurücksetzen',
    // Aktionsnamen der Tastenbelegung
    'key.forward': 'Vorwärts',
    'key.back': 'Rückwärts',
    'key.left': 'Links',
    'key.right': 'Rechts',
    'key.jump': 'Springen',
    'key.sneak': 'Schleichen',
    'key.sprint': 'Sprinten',
    'key.inventory': 'Inventar',
    'key.drop': 'Item fallen lassen',
    'key.chat': 'Chat',
    // Pause
    'pause.title': 'Pause',
    'pause.resume': 'Weiterspielen',
    'pause.save': 'Speichern',
    'pause.saved': 'Gespeichert',
    'pause.biome': 'Biom-Teleport',
    'pause.mainMenu': 'Zurück zum Hauptmenü',
    // Laden / Biom-Teleport
    'loading.world': 'Welt wird generiert…',
    'biome.title': 'Biom-Teleport',
    'biome.prompt': 'Nächstes Vorkommen suchen und hinspringen:',
    // Hinweise
    'toast.clickToPlay': 'Klicken, um zu spielen',
    // Konto
    'acc.subtitle': 'Konto',
    'acc.login': 'Anmelden',
    'acc.register': 'Registrieren',
    'acc.username': 'Benutzername',
    'acc.password': 'Passwort',
    'acc.loginBtn': 'Anmelden ▶',
    'acc.registerBtn': 'Konto erstellen ▶',
    'acc.hintLogin': 'Melde dich mit deinem Konto an.',
    'acc.hintRegister': 'Wähle Name (3–20 Zeichen) und Passwort (mind. 6 Zeichen).',
    'acc.needBoth': 'Bitte Name und Passwort eingeben.',
    'acc.working': 'Moment …',
    'acc.notConfigured': 'Noch kein Account-Server eingetragen (js/authconfig.js).',
    'acc.loggedIn': 'Angemeldet als',
    'acc.logout': 'Abmelden',
    // ---- Im Spiel: Inventar & Panels ----
    'inv.craft': 'Handwerk',
    'inv.anvil': 'Amboss',
    'inv.enchant': 'Verzauberungstisch',
    'inv.furnace': 'Ofen',
    'inv.chest': 'Truhe',
    'inv.brewing': 'Braustand',
    'inv.washer': 'Washer',
    'inv.trade': 'Handel',
    'inv.backpack': 'Rucksack',
    'inv.inventory': 'Inventar',
    'inv.clearSlots': 'Slots leeren',
    'inv.clearSlotsTip': 'Entfernt alle Upgrades — Materialien gehen verloren',
    'inv.anvilCost': 'Kosten: Sockel <b>{0}</b> · Aufwerten <b>{1}</b> Lvl<br>du hast <b>{2}</b> Level',
    'inv.enchantPrompt': 'Lege ein Werkzeug, eine Waffe, Rüstung oder einen Rucksack ein.',
    'inv.enchantNone': 'keine passende',
    'inv.enchantCost': '{0} Level · {1} Smaragde oder {2} Saphir',
    'inv.enchantHave': 'Du hast <b>{0}</b> Level · <b>{1}</b> Smaragde · <b>{2}</b> Saphire',
    'inv.fuel': '🔥 Brennstoff',
    'inv.bottles': 'Flaschen',
    'inv.water': 'Wasser',
    'inv.ingredient': 'Zutat',
    'inv.fluxDust': 'Flux-Staub',
    'inv.tradeInfo': 'Level {0} — {1}/{2} Angebote frei',
    'inv.tradeNext': ' · noch {0} Handel bis zum nächsten Slot',
    'inv.tradeFull': ' · voll ausgebaut',
    'inv.creativeAll': 'Alle Blöcke & Items (Klick = Stapel, Rechtsklick = einzeln)',
    'inv.durability': 'Haltbarkeit',
    // Seltenheit & Verzauberungen
    'rarity.common': 'Gewöhnlich',
    'rarity.uncommon': 'Ungewöhnlich',
    'rarity.rare': 'Selten',
    'ench.unbreakable': 'Unzerbrechlich',
    'ench.efficiency': 'Effizienz',
    'ench.sharpness': 'Schärfe',
    'ench.protection': 'Schutz',
    'ench.space': 'Stauraum',
    // ---- Im Spiel: Meldungen (Toasts) ----
    'hud.flyOn': 'Fliegen an',
    'hud.flyOff': 'Fliegen aus',
    'hud.spectatorOn': 'Spectator an (durch Blöcke fliegen)',
    'hud.spectatorOff': 'Spectator aus',
    'hud.broke': '{0} ist zerbrochen!',
    'hud.spellFades': 'Die Zauberwirkung verfliegt …',
    'hud.spawnSet': 'Spawnpunkt gesetzt',
    'hud.spawnSetNight': 'Spawnpunkt gesetzt — schlafen geht nur nachts',
    'hud.fxMining': '⛏ Schürfblick: Erze leuchten 5 Minuten durch das Gestein!',
    'hud.fxWater': '🌊 Wasseratmung: 5 Minuten Luft unter Wasser!',
    'hud.fxLevitation': '🕊 Levitation: 5 Minuten fliegen (2× Leertaste)!',
    'hud.notEnoughXp': 'Nicht genug XP: {0} Level nötig',
    'hud.notEnoughGems': 'Nicht genug Edelsteine: {0} Smaragde oder {1} Saphir',
    'hud.enchanted': '{0} {1} verzaubert!',
    'hud.chestSealed': 'Die Truhe ist noch versiegelt — besiege alle Wächter!',
    'hud.chestWave1': '⚔ Die Truhe erwacht! Welle 1: Wächter greifen an!',
    'hud.chestWave2': '⚔ Welle 2: MEGA-Zombies! Vorsicht!',
    'hud.chestUnsealed': '✨ Die Truhe ist entsiegelt!',
    'hud.welcomeBack': 'Willkommen zurück — dein Stand wurde wiederhergestellt. T für Chat',
    'hud.connected': 'Verbunden — Seed {0}. T für Chat',
    'hud.connLost': '⚠ Verbindung zum Server verloren',
    'hud.connLostChat': 'Verbindung zum Server verloren',
    'hud.becameHost': '👑 Du bist jetzt der Host — Mobs laufen auf deinem Gerät',
    'hud.kicked': '⚠ Du wurdest vom Server geworfen',
    'hud.banned': '⛔ Du wurdest von diesem Server gebannt',
    'hud.authfailDefault': 'Konto-Anmeldung ungültig',
    'hud.playerDied': '{0} ist gestorben',
    'hud.someone': 'Ein Spieler',
    'hud.teleported': '➤ Teleportiert',
    'hud.healed': '❤ Voll geheilt',
    'hud.fed': '🍖 Gesättigt',
    'hud.itemUnknown': 'Item „{0}" unbekannt',
    'hud.received': 'Erhalten: {0}× {1}',
    'hud.invincible': '🛡 Unverwundbar: {0}',
    'hud.flying': '🕊 Fliegen: {0}',
    'hud.gamemode': 'Spielmodus: {0}',
    'hud.invCleared': '🗑 Inventar geleert',
    'hud.on': 'AN',
    'hud.off': 'AUS',
    'hud.creative': 'Kreativ',
    'hud.survival': 'Überleben',
    // ---- Debug-Overlay (F3) ----
    'dbg.mode': 'Modus',
    'dbg.status': 'Status',
    'dbg.speed': 'Tempo',
    'dbg.speedUnit': '{0} B/s horizontal · {1} vertikal',
    'dbg.facing': 'Blick',
    'dbg.biome': 'Biom',
    'dbg.climate': 'Klima',
    'dbg.surface': 'Oberfläche',
    'dbg.lightHere': 'Licht hier',
    'dbg.time': 'Zeit',
    'dbg.day': 'Tag',
    'dbg.night': '☾ Nacht',
    'dbg.dayLabel': '☀ Tag',
    'dbg.spawn': 'Spawn',
    'dbg.spawnBed': '(Bett)',
    'dbg.spawnWorld': 'Welt-Spawn',
    'dbg.effects': 'Effekte',
    'dbg.target': 'Ziel',
    'dbg.hand': 'Hand',
    'dbg.hardness': 'Härte',
    'dbg.tool': 'Werkzeug',
    'dbg.tier': 'Stufe',
    'dbg.light': 'Licht',
    'dbg.onGround': 'am Boden',
    'dbg.inAir': 'in der Luft',
    'dbg.inWater': 'im Wasser',
    'dbg.inLava': 'in Lava!',
    'dbg.climbing': 'klettert',
    'dbg.flyingState': 'fliegt',
    'dbg.lightVal': 'Himmel {0} / Block {1}',
    'dbg.dirN': 'Norden (−z)',
    'dbg.dirS': 'Süden (+z)',
    'dbg.dirE': 'Osten (+x)',
    'dbg.dirW': 'Westen (−x)',
    'dbg.loaded': 'geladen',
    'dbg.generated': 'generiert',
    'dbg.meshed': 'gemesht',
    'dbg.triangles': 'Dreiecke',
    'dbg.gpuMem': 'GPU-Speicher',
    'dbg.geometries': 'Geometrien',
    'dbg.textures': 'Texturen',
    'dbg.particles': 'Partikel',
    'dbg.furnaces': 'Öfen',
    'dbg.chests2': 'Truhen',
    'dbg.water': 'Wasser',
    'dbg.cells': 'Zellen',
    'dbg.spray': 'Gischt',
    'dbg.sparks': 'Funken',
    'dbg.leafQueue': 'Laub-Queue',
    'dbg.saplings': 'Setzlinge',
    'dbg.crystals': 'Kristalle',
    'dbg.worldEdits': 'Welt-Edits',
    'dbg.blocks': 'Blöcke',
    'dbg.save': 'Spielstand',
  },
  en: {
    // Main menu
    'menu.singleplayer': 'Singleplayer',
    'menu.multiplayer': 'Multiplayer',
    'menu.settings': 'Settings',
    'menu.quit': 'Quit',
    'menu.back': '‹ Back',
    // Singleplayer
    'sp.seedPlaceholder': 'Seed (empty = random)',
    'sp.modeSurvival': 'Game mode: Survival',
    'sp.modeCreative': 'Game mode: Creative',
    'sp.newWorld': 'New World',
    'sp.continue': 'Continue World',
    'sp.delete': 'Delete World',
    'sp.deleteConfirm': 'Really delete the saved world?',
    'sp.deleted': 'World deleted',
    'sp.worldName': 'World name (empty = auto)',
    'sp.create': 'Create new world',
    'sp.savedWorlds': 'Saved worlds',
    'sp.noWorlds': 'No saved worlds yet',
    'sp.load': 'Load',
    'sp.creative': 'Creative',
    'sp.survival': 'Survival',
    // Multiplayer
    'mp.namePlaceholder': 'Player name',
    'mp.joinAs': 'Join as:',
    'mp.addrPlaceholder': 'Server address (empty = this server)',
    'mp.join': 'Join multiplayer',
    'mp.rejoin': 'Reconnect',
    'mp.defaultName': 'Player',
    'mp.prevServers': 'Previous servers',
    'mp.noServers': 'No servers yet',
    'mp.connect': 'Connect',
    'mp.online': 'Online',
    'mp.offline': 'Offline',
    'mp.checking': 'Checking …',
    'mp.thisServer': 'This server',
    // Settings
    'set.title': 'Settings',
    'set.language': 'Language',
    'set.renderDistance': 'Render distance: {0} chunks ({1} blocks)',
    'set.renderHint': 'Full voxel detail up to {0} chunks — beyond that, distant terrain is ' +
      'simplified (height profile with biome colors). Very high values cost performance. ' +
      'Applies instantly, no restart.',
    'set.creativeSpeed': 'Creative movement speed: ×{0}',
    'set.done': 'Done',
    'set.close': 'Close',
    // Sections & new options
    'set.sec.graphics': 'Graphics',
    'set.sec.performance': 'Performance',
    'set.sec.controls': 'Controls',
    'set.clouds': 'Clouds in the sky',
    'set.on': 'On',
    'set.off': 'Off',
    'set.maxFps': 'Frame rate limit: {0}',
    'set.unlimited': 'Unlimited',
    'set.vsync': 'VSync (sync to monitor)',
    'set.vsyncHint': 'VSync locks the frame rate to your monitor (smooth, no tearing). ' +
      'Turn VSync off to use the frame rate limit.',
    'set.rebindHint': 'Click to change, then press a new key · Esc cancels',
    'set.rebindWait': '… press a key …',
    'set.resetKeys': 'Reset controls',
    // Keybind action names
    'key.forward': 'Forward',
    'key.back': 'Backward',
    'key.left': 'Left',
    'key.right': 'Right',
    'key.jump': 'Jump',
    'key.sneak': 'Sneak',
    'key.sprint': 'Sprint',
    'key.inventory': 'Inventory',
    'key.drop': 'Drop item',
    'key.chat': 'Chat',
    // Pause
    'pause.title': 'Pause',
    'pause.resume': 'Resume',
    'pause.save': 'Save',
    'pause.saved': 'Saved',
    'pause.biome': 'Biome teleport',
    'pause.mainMenu': 'Back to main menu',
    // Loading / biome teleport
    'loading.world': 'Generating world…',
    'biome.title': 'Biome teleport',
    'biome.prompt': 'Find the nearest occurrence and jump there:',
    // Toasts
    'toast.clickToPlay': 'Click to play',
    // Account
    'acc.subtitle': 'Account',
    'acc.login': 'Log in',
    'acc.register': 'Register',
    'acc.username': 'Username',
    'acc.password': 'Password',
    'acc.loginBtn': 'Log in ▶',
    'acc.registerBtn': 'Create account ▶',
    'acc.hintLogin': 'Log in with your account.',
    'acc.hintRegister': 'Choose a name (3–20 chars) and password (min. 6 chars).',
    'acc.needBoth': 'Please enter name and password.',
    'acc.working': 'Please wait …',
    'acc.notConfigured': 'No account server set yet (js/authconfig.js).',
    'acc.loggedIn': 'Logged in as',
    'acc.logout': 'Log out',
    // ---- In game: inventory & panels ----
    'inv.craft': 'Crafting',
    'inv.anvil': 'Anvil',
    'inv.enchant': 'Enchanting Table',
    'inv.furnace': 'Furnace',
    'inv.chest': 'Chest',
    'inv.brewing': 'Brewing Stand',
    'inv.washer': 'Washer',
    'inv.trade': 'Trading',
    'inv.backpack': 'Backpack',
    'inv.inventory': 'Inventory',
    'inv.clearSlots': 'Clear slots',
    'inv.clearSlotsTip': 'Removes all upgrades — materials are lost',
    'inv.anvilCost': 'Cost: Socket <b>{0}</b> · Upgrade <b>{1}</b> lvl<br>you have <b>{2}</b> levels',
    'inv.enchantPrompt': 'Insert a tool, weapon, armor or backpack.',
    'inv.enchantNone': 'none suitable',
    'inv.enchantCost': '{0} levels · {1} emeralds or {2} sapphire',
    'inv.enchantHave': 'You have <b>{0}</b> levels · <b>{1}</b> emeralds · <b>{2}</b> sapphires',
    'inv.fuel': '🔥 Fuel',
    'inv.bottles': 'Bottles',
    'inv.water': 'Water',
    'inv.ingredient': 'Ingredient',
    'inv.fluxDust': 'Flux dust',
    'inv.tradeInfo': 'Level {0} — {1}/{2} offers unlocked',
    'inv.tradeNext': ' · {0} more trades to next slot',
    'inv.tradeFull': ' · fully unlocked',
    'inv.creativeAll': 'All blocks & items (click = stack, right-click = single)',
    'inv.durability': 'Durability',
    // Rarity & enchantments
    'rarity.common': 'Common',
    'rarity.uncommon': 'Uncommon',
    'rarity.rare': 'Rare',
    'ench.unbreakable': 'Unbreakable',
    'ench.efficiency': 'Efficiency',
    'ench.sharpness': 'Sharpness',
    'ench.protection': 'Protection',
    'ench.space': 'Space',
    // ---- In game: messages (toasts) ----
    'hud.flyOn': 'Flying on',
    'hud.flyOff': 'Flying off',
    'hud.spectatorOn': 'Spectator on (fly through blocks)',
    'hud.spectatorOff': 'Spectator off',
    'hud.broke': '{0} broke!',
    'hud.spellFades': 'The spell fades …',
    'hud.spawnSet': 'Spawn point set',
    'hud.spawnSetNight': 'Spawn point set — you can only sleep at night',
    'hud.fxMining': '⛏ Miner’s sight: ores glow through stone for 5 minutes!',
    'hud.fxWater': '🌊 Water breathing: 5 minutes of air underwater!',
    'hud.fxLevitation': '🕊 Levitation: fly for 5 minutes (double-space)!',
    'hud.notEnoughXp': 'Not enough XP: {0} levels needed',
    'hud.notEnoughGems': 'Not enough gems: {0} emeralds or {1} sapphire',
    'hud.enchanted': 'Enchanted {0} {1}!',
    'hud.chestSealed': 'The chest is still sealed — defeat all guardians!',
    'hud.chestWave1': '⚔ The chest awakens! Wave 1: guardians attack!',
    'hud.chestWave2': '⚔ Wave 2: MEGA zombies! Watch out!',
    'hud.chestUnsealed': '✨ The chest is unsealed!',
    'hud.welcomeBack': 'Welcome back — your progress was restored. T to chat',
    'hud.connected': 'Connected — seed {0}. T to chat',
    'hud.connLost': '⚠ Lost connection to the server',
    'hud.connLostChat': 'Lost connection to the server',
    'hud.becameHost': '👑 You are the host now — mobs run on your device',
    'hud.kicked': '⚠ You were kicked from the server',
    'hud.banned': '⛔ You were banned from this server',
    'hud.authfailDefault': 'Account login invalid',
    'hud.playerDied': '{0} has died',
    'hud.someone': 'A player',
    'hud.teleported': '➤ Teleported',
    'hud.healed': '❤ Fully healed',
    'hud.fed': '🍖 Fed',
    'hud.itemUnknown': 'Item “{0}” unknown',
    'hud.received': 'Received: {0}× {1}',
    'hud.invincible': '🛡 Invincible: {0}',
    'hud.flying': '🕊 Flying: {0}',
    'hud.gamemode': 'Game mode: {0}',
    'hud.invCleared': '🗑 Inventory cleared',
    'hud.on': 'ON',
    'hud.off': 'OFF',
    'hud.creative': 'Creative',
    'hud.survival': 'Survival',
    // ---- Debug overlay (F3) ----
    'dbg.mode': 'Mode',
    'dbg.status': 'Status',
    'dbg.speed': 'Speed',
    'dbg.speedUnit': '{0} b/s horizontal · {1} vertical',
    'dbg.facing': 'Facing',
    'dbg.biome': 'Biome',
    'dbg.climate': 'Climate',
    'dbg.surface': 'Surface',
    'dbg.lightHere': 'Light here',
    'dbg.time': 'Time',
    'dbg.day': 'Day',
    'dbg.night': '☾ Night',
    'dbg.dayLabel': '☀ Day',
    'dbg.spawn': 'Spawn',
    'dbg.spawnBed': '(bed)',
    'dbg.spawnWorld': 'World spawn',
    'dbg.effects': 'Effects',
    'dbg.target': 'Target',
    'dbg.hand': 'Hand',
    'dbg.hardness': 'Hardness',
    'dbg.tool': 'Tool',
    'dbg.tier': 'Tier',
    'dbg.light': 'Light',
    'dbg.onGround': 'on ground',
    'dbg.inAir': 'in the air',
    'dbg.inWater': 'in water',
    'dbg.inLava': 'in lava!',
    'dbg.climbing': 'climbing',
    'dbg.flyingState': 'flying',
    'dbg.lightVal': 'sky {0} / block {1}',
    'dbg.dirN': 'North (−z)',
    'dbg.dirS': 'South (+z)',
    'dbg.dirE': 'East (+x)',
    'dbg.dirW': 'West (−x)',
    'dbg.loaded': 'loaded',
    'dbg.generated': 'generated',
    'dbg.meshed': 'meshed',
    'dbg.triangles': 'Triangles',
    'dbg.gpuMem': 'GPU memory',
    'dbg.geometries': 'Geometries',
    'dbg.textures': 'Textures',
    'dbg.particles': 'Particles',
    'dbg.furnaces': 'Furnaces',
    'dbg.chests2': 'Chests',
    'dbg.water': 'Water',
    'dbg.cells': 'cells',
    'dbg.spray': 'Spray',
    'dbg.sparks': 'Sparks',
    'dbg.leafQueue': 'Leaf queue',
    'dbg.saplings': 'Saplings',
    'dbg.crystals': 'Crystals',
    'dbg.worldEdits': 'World edits',
    'dbg.blocks': 'blocks',
    'dbg.save': 'Save',
  },
};

// Lustige Zufalls-Sprüche fürs Hauptmenü (Minecraft-Stil), je Sprache.
const SPLASHES = {
  de: [
    'Zu 100 % aus Pixeln!', 'Jetzt mit noch mehr Blöcken!', 'Kein einziges Bild-Asset!',
    'Prozedural bis in die Wurzeln!', 'Vorsicht vor Creepern!', 'Grüße an alle Dorfbewohner!',
    'Baumfrei? Niemals!', 'Enthält Spuren von Diamanten.', 'Hergestellt aus Seed und Liebe.',
    'Auch offline spielbar!', 'Drück nicht auf den roten Block!', 'Frisch aus dem Ofen!',
    'Mehr Bäume als dein Browser verträgt!', 'Jetzt mit Regenbogen-Holz!', 'Nachts wird’s gruselig.',
    'Schaufel nicht mitgeliefert.', 'Läuft sogar auf dem Toaster!', 'Voxelig!', 'Mind. 19 Biome!',
    'Bau dir dein eigenes Schloss!', 'Zombies hassen diesen Trick!', 'Der Seed war’s!',
    'Grabe niemals gerade nach unten!', 'Blockig und stolz drauf!', 'Katzenvideos nicht enthalten.',
    'Wo ist mein Bett?', 'Kein Handbuch, viel Spaß!', 'Achtung, Suchtgefahr!',
    'Iss dein Gemüse … oder Schweine.', 'Kühe geben hier keine Milch … oder doch?',
  ],
  en: [
    'Made of 100% pixels!', 'Now with even more blocks!', 'Not a single image asset!',
    'Procedural to the core!', 'Beware of creepers!', 'Say hi to the villagers!',
    'Tree-free? Never!', 'Contains traces of diamonds.', 'Made with seed and love.',
    'Playable offline too!', 'Do not press the red block!', 'Fresh out of the furnace!',
    'More trees than your browser can handle!', 'Now with rainbow wood!', 'It gets spooky at night.',
    'Shovel not included.', 'Runs on a toaster!', 'Voxelicious!', 'At least 19 biomes!',
    'Build your own castle!', 'Zombies hate this trick!', 'The seed did it!',
    'Never dig straight down!', 'Blocky and proud!', 'Cat videos not included.',
    'Where is my bed?', 'No manual, have fun!', 'Warning: highly addictive!',
    'Eat your veggies … or pigs.', 'Cows give no milk here … or do they?',
  ],
};

const _listeners = [];

export function getLang() {
  return LANGS[Settings.lang] ? Settings.lang : 'de';
}

export function setLang(l) {
  if (l !== 'de' && l !== 'en') return;
  Settings.lang = l;
  Settings.save();
  for (const cb of _listeners) { try { cb(l); } catch { /* Listener-Fehler nie fatal */ } }
}

// Callback bei jedem Sprachwechsel — die UI hängt hier ihre Neu-Übersetzung ein.
export function onLangChange(cb) { _listeners.push(cb); }

// Übersetzt key in die aktive Sprache; fehlt der Schlüssel, Fallback auf Deutsch, dann key selbst.
export function t(key, ...args) {
  const lang = getLang();
  let s = LANGS[lang] && LANGS[lang][key];
  if (s == null) s = LANGS.de[key];
  if (s == null) return key;
  return s.replace(/\{(\d+)\}/g, (m, i) => (args[i] !== undefined ? args[i] : m));
}

// Ein zufälliger Menü-Spruch in der aktiven Sprache.
export function randomSplash() {
  const list = SPLASHES[getLang()] || SPLASHES.de;
  return list[Math.floor(Math.random() * list.length)];
}
