// Englische Namen für Blöcke, Items & Biome. Wird beim Start einmal eingebunden
// (main.js) und hängt jedem Block/Item ein .nameEn an — nameOf() in constants.js wählt
// anhand der Sprache. Die deutschen Namen bleiben die Quelle in constants.js;
// fehlt hier ein Eintrag, fällt nameOf() automatisch auf Deutsch zurück.
import { BLOCK, ITEM, BLOCKS, ITEMS } from './constants.js';

const BLOCK_EN = {
  [BLOCK.GRASS]: 'Grass Block', [BLOCK.DIRT]: 'Dirt', [BLOCK.STONE]: 'Stone',
  [BLOCK.COBBLESTONE]: 'Cobblestone', [BLOCK.LOG]: 'Oak Log', [BLOCK.PLANKS]: 'Oak Planks',
  [BLOCK.LEAVES]: 'Oak Leaves', [BLOCK.SAND]: 'Sand', [BLOCK.WATER]: 'Water',
  [BLOCK.BEDROCK]: 'Bedrock', [BLOCK.COAL_ORE]: 'Coal Ore', [BLOCK.IRON_ORE]: 'Iron Ore',
  [BLOCK.CRAFTING_TABLE]: 'Crafting Table', [BLOCK.SNOW]: 'Snow', [BLOCK.SNOWY_GRASS]: 'Snowy Grass Block',
  [BLOCK.BIRCH_LOG]: 'Birch Log', [BLOCK.BIRCH_LEAVES]: 'Birch Leaves',
  [BLOCK.SPRUCE_LOG]: 'Spruce Log', [BLOCK.SPRUCE_LEAVES]: 'Spruce Leaves',
  [BLOCK.RED_SAND]: 'Red Sand', [BLOCK.TERRACOTTA]: 'Terracotta', [BLOCK.TERRACOTTA_RED]: 'Red Terracotta',
  [BLOCK.MYCELIUM]: 'Mycelium', [BLOCK.MUSHROOM_STEM]: 'Mushroom Stem',
  [BLOCK.MUSHROOM_CAP_RED]: 'Red Mushroom Cap', [BLOCK.MUSHROOM_CAP_BROWN]: 'Brown Mushroom Cap',
  [BLOCK.SAVANNA_GRASS]: 'Savanna Grass', [BLOCK.FLOWER_RED]: 'Poppy', [BLOCK.FLOWER_YELLOW]: 'Dandelion',
  [BLOCK.TALL_GRASS]: 'Tall Grass', [BLOCK.LAVA]: 'Lava', [BLOCK.DRIPSTONE]: 'Dripstone',
  [BLOCK.MOSS]: 'Moss Block', [BLOCK.CAVE_VINE]: 'Cave Vine',
  [BLOCK.WATER_FLOW7]: 'Water', [BLOCK.WATER_FLOW6]: 'Water', [BLOCK.WATER_FLOW5]: 'Water',
  [BLOCK.WATER_FLOW4]: 'Water', [BLOCK.WATER_FLOW3]: 'Water', [BLOCK.WATER_FLOW2]: 'Water',
  [BLOCK.WATER_FLOW1]: 'Water', [BLOCK.LAVA_FLOW6]: 'Lava', [BLOCK.LAVA_FLOW4]: 'Lava',
  [BLOCK.LAVA_FLOW2]: 'Lava', [BLOCK.TORCH]: 'Torch', [BLOCK.GRAVEL]: 'Gravel',
  [BLOCK.SUGAR_CANE]: 'Sugar Cane', [BLOCK.ANVIL]: 'Anvil', [BLOCK.GOLD_ORE]: 'Gold Ore',
  [BLOCK.DIAMOND_ORE]: 'Diamond Ore', [BLOCK.FURNACE]: 'Furnace', [BLOCK.FURNACE_ON]: 'Furnace',
  [BLOCK.SAPLING]: 'Oak Sapling', [BLOCK.BIRCH_SAPLING]: 'Birch Sapling', [BLOCK.SPRUCE_SAPLING]: 'Spruce Sapling',
  [BLOCK.TNT]: 'TNT', [BLOCK.CHEST]: 'Chest', [BLOCK.GLASS]: 'Glass', [BLOCK.GLASS_PANE]: 'Glass Pane',
  [BLOCK.PLANK_SLAB]: 'Oak Slab', [BLOCK.PLANK_SLAB_TOP]: 'Oak Slab',
  [BLOCK.COBBLE_SLAB]: 'Cobblestone Slab', [BLOCK.COBBLE_SLAB_TOP]: 'Cobblestone Slab',
  [BLOCK.PLANK_STAIRS_E]: 'Oak Stairs', [BLOCK.PLANK_STAIRS_W]: 'Oak Stairs',
  [BLOCK.PLANK_STAIRS_S]: 'Oak Stairs', [BLOCK.PLANK_STAIRS_N]: 'Oak Stairs',
  [BLOCK.COBBLE_STAIRS_E]: 'Cobblestone Stairs', [BLOCK.COBBLE_STAIRS_W]: 'Cobblestone Stairs',
  [BLOCK.COBBLE_STAIRS_S]: 'Cobblestone Stairs', [BLOCK.COBBLE_STAIRS_N]: 'Cobblestone Stairs',
  [BLOCK.LADDER]: 'Ladder', [BLOCK.TRAPDOOR]: 'Trapdoor',
  [BLOCK.TRAPDOOR_OPEN_N]: 'Trapdoor', [BLOCK.TRAPDOOR_OPEN_E]: 'Trapdoor',
  [BLOCK.TRAPDOOR_OPEN_S]: 'Trapdoor', [BLOCK.TRAPDOOR_OPEN_W]: 'Trapdoor',
  [BLOCK.DOOR_LOWER_N]: 'Door', [BLOCK.DOOR_LOWER_E]: 'Door', [BLOCK.DOOR_LOWER_S]: 'Door',
  [BLOCK.DOOR_LOWER_W]: 'Door', [BLOCK.DOOR_UPPER_N]: 'Door', [BLOCK.DOOR_UPPER_E]: 'Door',
  [BLOCK.DOOR_UPPER_S]: 'Door', [BLOCK.DOOR_UPPER_W]: 'Door',
  [BLOCK.CARPET]: 'Carpet', [BLOCK.CARPET_RED]: 'Red Carpet', [BLOCK.CARPET_YELLOW]: 'Yellow Carpet',
  [BLOCK.CARPET_WHITE]: 'White Carpet', [BLOCK.BED_FOOT]: 'Bed', [BLOCK.BED_HEAD]: 'Bed',
  [BLOCK.PLANK_STAIRS_E_TOP]: 'Oak Stairs', [BLOCK.PLANK_STAIRS_W_TOP]: 'Oak Stairs',
  [BLOCK.PLANK_STAIRS_S_TOP]: 'Oak Stairs', [BLOCK.PLANK_STAIRS_N_TOP]: 'Oak Stairs',
  [BLOCK.COBBLE_STAIRS_E_TOP]: 'Cobblestone Stairs', [BLOCK.COBBLE_STAIRS_W_TOP]: 'Cobblestone Stairs',
  [BLOCK.COBBLE_STAIRS_S_TOP]: 'Cobblestone Stairs', [BLOCK.COBBLE_STAIRS_N_TOP]: 'Cobblestone Stairs',
  [BLOCK.WOOL]: 'Wool', [BLOCK.SEAGRASS]: 'Seagrass', [BLOCK.KELP]: 'Kelp',
  [BLOCK.SHRUB]: 'Dead Bush', [BLOCK.CACTUS]: 'Cactus', [BLOCK.CACTUS_FLOWER]: 'Cactus Flower',
  [BLOCK.SANDSTONE]: 'Sandstone', [BLOCK.VINE]: 'Vines', [BLOCK.STONE_BRICKS]: 'Stone Bricks',
  [BLOCK.CRACKED_STONE_BRICKS]: 'Cracked Stone Bricks', [BLOCK.MOSSY_STONE_BRICKS]: 'Mossy Stone Bricks',
  [BLOCK.LOOT_CHEST]: 'Sealed Chest', [BLOCK.CRYSTAL_BLUE]: 'Blue Crystal',
  [BLOCK.CRYSTAL_PURPLE]: 'Purple Crystal', [BLOCK.CRYSTAL_GREEN]: 'Green Crystal',
  [BLOCK.CRYSTAL_ORANGE]: 'Orange Crystal', [BLOCK.GLASS_BLUE]: 'Blue Glass',
  [BLOCK.GLASS_PURPLE]: 'Purple Glass', [BLOCK.GLASS_GREEN]: 'Green Glass', [BLOCK.GLASS_ORANGE]: 'Orange Glass',
  [BLOCK.TOWER_CHEST]: 'Mage Chest', [BLOCK.IRON_BLOCK]: 'Iron Block', [BLOCK.GOLD_BLOCK]: 'Gold Block',
  [BLOCK.DIAMOND_BLOCK]: 'Diamond Block', [BLOCK.WRECK_CHEST]: 'Shipwreck Chest',
  [BLOCK.MOSSY_COBBLESTONE]: 'Mossy Cobblestone', [BLOCK.PEBBLES]: 'Pebbles',
  [BLOCK.DUNGEON_CHEST]: 'Dungeon Chest', [BLOCK.COBWEB]: 'Cobweb', [BLOCK.SPAWNER]: 'Monster Spawner',
  [BLOCK.FARMLAND]: 'Farmland', [BLOCK.FARMLAND_WET]: 'Wet Farmland',
  [BLOCK.WHEAT_0]: 'Wheat (Stage 1)', [BLOCK.WHEAT_1]: 'Wheat (Stage 2)',
  [BLOCK.WHEAT_2]: 'Wheat (Stage 3)', [BLOCK.WHEAT_3]: 'Wheat (Stage 4)',
  [BLOCK.CARROT_0]: 'Carrots (Stage 1)', [BLOCK.CARROT_1]: 'Carrots (Stage 2)',
  [BLOCK.CARROT_2]: 'Carrots (Stage 3)', [BLOCK.CARROT_3]: 'Carrots (Stage 4)',
  [BLOCK.POTATO_0]: 'Potatoes (Stage 1)', [BLOCK.POTATO_1]: 'Potatoes (Stage 2)',
  [BLOCK.POTATO_2]: 'Potatoes (Stage 3)', [BLOCK.POTATO_3]: 'Potatoes (Stage 4)',
  [BLOCK.BOSS_SPAWNER]: 'Blood Core', [BLOCK.BREWING_STAND]: 'Brewing Stand',
  [BLOCK.REDSTONE_DUST]: 'Flux Dust', [BLOCK.REDSTONE_DUST_ON]: 'Flux Dust',
  [BLOCK.LEVER]: 'Lever', [BLOCK.LEVER_ON]: 'Lever', [BLOCK.BUTTON]: 'Button', [BLOCK.BUTTON_ON]: 'Button',
  [BLOCK.PISTON_N]: 'Piston', [BLOCK.PISTON_E]: 'Piston', [BLOCK.PISTON_S]: 'Piston', [BLOCK.PISTON_W]: 'Piston',
  [BLOCK.PISTON_HEAD]: 'Piston Head', [BLOCK.FLUX_ORE]: 'Flux Ore', [BLOCK.WASHER]: 'Washer',
  [BLOCK.FLUX_BLOCK]: 'Flux Block',
  [BLOCK.STICKY_PISTON_N]: 'Sticky Piston', [BLOCK.STICKY_PISTON_E]: 'Sticky Piston',
  [BLOCK.STICKY_PISTON_S]: 'Sticky Piston', [BLOCK.STICKY_PISTON_W]: 'Sticky Piston',
  [BLOCK.PISTON_UP]: 'Piston', [BLOCK.PISTON_DOWN]: 'Piston',
  [BLOCK.STICKY_PISTON_UP]: 'Sticky Piston', [BLOCK.STICKY_PISTON_DOWN]: 'Sticky Piston',
  [BLOCK.JUNGLE_LOG]: 'Jungle Log', [BLOCK.JUNGLE_BUSH]: 'Jungle Bush',
  [BLOCK.HANGING_ROOTS]: 'Hanging Roots', [BLOCK.ROOTED_DIRT]: 'Rooted Dirt', [BLOCK.GLOW_LICHEN]: 'Glow Lichen',
  [BLOCK.EMERALD_ORE]: 'Emerald Ore', [BLOCK.SAPPHIRE_ORE]: 'Sapphire Ore',
  [BLOCK.BIRCH_PLANKS]: 'Birch Planks', [BLOCK.SPRUCE_PLANKS]: 'Spruce Planks', [BLOCK.JUNGLE_PLANKS]: 'Jungle Planks',
  [BLOCK.BIRCH_SLAB]: 'Birch Slab', [BLOCK.BIRCH_SLAB_TOP]: 'Birch Slab',
  [BLOCK.SPRUCE_SLAB]: 'Spruce Slab', [BLOCK.SPRUCE_SLAB_TOP]: 'Spruce Slab',
  [BLOCK.JUNGLE_SLAB]: 'Jungle Slab', [BLOCK.JUNGLE_SLAB_TOP]: 'Jungle Slab',
  [BLOCK.BIRCH_STAIRS_E]: 'Birch Stairs', [BLOCK.BIRCH_STAIRS_W]: 'Birch Stairs',
  [BLOCK.BIRCH_STAIRS_S]: 'Birch Stairs', [BLOCK.BIRCH_STAIRS_N]: 'Birch Stairs',
  [BLOCK.SPRUCE_STAIRS_E]: 'Spruce Stairs', [BLOCK.SPRUCE_STAIRS_W]: 'Spruce Stairs',
  [BLOCK.SPRUCE_STAIRS_S]: 'Spruce Stairs', [BLOCK.SPRUCE_STAIRS_N]: 'Spruce Stairs',
  [BLOCK.JUNGLE_STAIRS_E]: 'Jungle Stairs', [BLOCK.JUNGLE_STAIRS_W]: 'Jungle Stairs',
  [BLOCK.JUNGLE_STAIRS_S]: 'Jungle Stairs', [BLOCK.JUNGLE_STAIRS_N]: 'Jungle Stairs',
  [BLOCK.BIRCH_STAIRS_E_TOP]: 'Birch Stairs', [BLOCK.BIRCH_STAIRS_W_TOP]: 'Birch Stairs',
  [BLOCK.BIRCH_STAIRS_S_TOP]: 'Birch Stairs', [BLOCK.BIRCH_STAIRS_N_TOP]: 'Birch Stairs',
  [BLOCK.SPRUCE_STAIRS_E_TOP]: 'Spruce Stairs', [BLOCK.SPRUCE_STAIRS_W_TOP]: 'Spruce Stairs',
  [BLOCK.SPRUCE_STAIRS_S_TOP]: 'Spruce Stairs', [BLOCK.SPRUCE_STAIRS_N_TOP]: 'Spruce Stairs',
  [BLOCK.JUNGLE_STAIRS_E_TOP]: 'Jungle Stairs', [BLOCK.JUNGLE_STAIRS_W_TOP]: 'Jungle Stairs',
  [BLOCK.JUNGLE_STAIRS_S_TOP]: 'Jungle Stairs', [BLOCK.JUNGLE_STAIRS_N_TOP]: 'Jungle Stairs',
  [BLOCK.PEBBLES_WET]: 'Pebbles',
  [BLOCK.BERRY_BUSH_RED]: 'Red Berry Bush', [BLOCK.BERRY_BUSH_BLUE]: 'Blue Berry Bush',
  [BLOCK.BERRY_BUSH_YELLOW]: 'Yellow Berry Bush',
  [BLOCK.LOG_X]: 'Oak Log', [BLOCK.LOG_Z]: 'Oak Log', [BLOCK.BIRCH_LOG_X]: 'Birch Log', [BLOCK.BIRCH_LOG_Z]: 'Birch Log',
  [BLOCK.SPRUCE_LOG_X]: 'Spruce Log', [BLOCK.SPRUCE_LOG_Z]: 'Spruce Log',
  [BLOCK.JUNGLE_LOG_X]: 'Jungle Log', [BLOCK.JUNGLE_LOG_Z]: 'Jungle Log',
  [BLOCK.DARK_GRASS]: 'Dark Grass Block', [BLOCK.MUSHROOM_RED]: 'Red Mushroom', [BLOCK.MUSHROOM_BROWN]: 'Brown Mushroom',
  [BLOCK.LEAFY_GRASS]: 'Leafy Grass', [BLOCK.OBSIDIAN]: 'Obsidian', [BLOCK.BOOKSHELF]: 'Bookshelf',
  [BLOCK.ENCHANTING_TABLE]: 'Enchanting Table',
};

const ITEM_EN = {
  [ITEM.STICK]: 'Stick', [ITEM.WOODEN_PICKAXE]: 'Wooden Pickaxe', [ITEM.WOODEN_AXE]: 'Wooden Axe',
  [ITEM.WOODEN_SHOVEL]: 'Wooden Shovel', [ITEM.WOODEN_SWORD]: 'Wooden Sword',
  [ITEM.STONE_PICKAXE]: 'Stone Pickaxe', [ITEM.STONE_AXE]: 'Stone Axe', [ITEM.STONE_SHOVEL]: 'Stone Shovel',
  [ITEM.STONE_SWORD]: 'Stone Sword', [ITEM.COAL]: 'Coal', [ITEM.RAW_IRON]: 'Raw Iron',
  [ITEM.PORKCHOP]: 'Raw Porkchop', [ITEM.ROTTEN_FLESH]: 'Rotten Flesh', [ITEM.APPLE]: 'Apple',
  [ITEM.FLINT]: 'Flint', [ITEM.SUGAR]: 'Sugar', [ITEM.RAW_GOLD]: 'Raw Gold', [ITEM.DIAMOND]: 'Diamond',
  [ITEM.IRON_PICKAXE]: 'Iron Pickaxe', [ITEM.IRON_AXE]: 'Iron Axe', [ITEM.IRON_SHOVEL]: 'Iron Shovel',
  [ITEM.IRON_SWORD]: 'Iron Sword', [ITEM.GOLD_PICKAXE]: 'Gold Pickaxe', [ITEM.GOLD_AXE]: 'Gold Axe',
  [ITEM.GOLD_SHOVEL]: 'Gold Shovel', [ITEM.GOLD_SWORD]: 'Gold Sword', [ITEM.DIAMOND_PICKAXE]: 'Diamond Pickaxe',
  [ITEM.DIAMOND_AXE]: 'Diamond Axe', [ITEM.DIAMOND_SHOVEL]: 'Diamond Shovel', [ITEM.DIAMOND_SWORD]: 'Diamond Sword',
  [ITEM.IRON_HELMET]: 'Iron Helmet', [ITEM.IRON_CHEST]: 'Iron Chestplate', [ITEM.IRON_LEGS]: 'Iron Leggings',
  [ITEM.IRON_BOOTS]: 'Iron Boots', [ITEM.GOLD_HELMET]: 'Gold Helmet', [ITEM.GOLD_CHEST]: 'Gold Chestplate',
  [ITEM.GOLD_LEGS]: 'Gold Leggings', [ITEM.GOLD_BOOTS]: 'Gold Boots', [ITEM.DIAMOND_HELMET]: 'Diamond Helmet',
  [ITEM.DIAMOND_CHEST]: 'Diamond Chestplate', [ITEM.DIAMOND_LEGS]: 'Diamond Leggings', [ITEM.DIAMOND_BOOTS]: 'Diamond Boots',
  [ITEM.IRON_INGOT]: 'Iron Ingot', [ITEM.GOLD_INGOT]: 'Gold Ingot', [ITEM.BONE]: 'Bone',
  [ITEM.GUNPOWDER]: 'Gunpowder', [ITEM.BONE_MEAL]: 'Bone Meal', [ITEM.FLINT_AND_STEEL]: 'Flint and Steel',
  [ITEM.SHEARS]: 'Shears', [ITEM.KELP]: 'Kelp', [ITEM.RAW_FISH]: 'Raw Fish', [ITEM.COOKED_FISH]: 'Cooked Fish',
  [ITEM.MUTTON]: 'Raw Mutton', [ITEM.COOKED_MUTTON]: 'Cooked Mutton', [ITEM.COOKED_PORKCHOP]: 'Cooked Porkchop',
  [ITEM.SOCKET_RUNE]: 'Socket Rune', [ITEM.CRYSTAL_BLUE_SHARD]: 'Crystal (Blue)', [ITEM.CRYSTAL_PURPLE_SHARD]: 'Crystal (Purple)',
  [ITEM.CRYSTAL_GREEN_SHARD]: 'Crystal (Green)', [ITEM.CRYSTAL_ORANGE_SHARD]: 'Crystal (Orange)',
  [ITEM.SCROLL_MINING]: 'Scroll of Mining', [ITEM.SCROLL_WATER]: 'Scroll of Water', [ITEM.SCROLL_LEVITATION]: 'Scroll of Levitation',
  [ITEM.PEBBLE]: 'Pebble', [ITEM.STRING]: 'String', [ITEM.BUCKET]: 'Bucket', [ITEM.WATER_BUCKET]: 'Water Bucket',
  [ITEM.LAVA_BUCKET]: 'Lava Bucket', [ITEM.WOODEN_HOE]: 'Wooden Hoe', [ITEM.STONE_HOE]: 'Stone Hoe',
  [ITEM.IRON_HOE]: 'Iron Hoe', [ITEM.WHEAT_SEEDS]: 'Wheat Seeds', [ITEM.WHEAT]: 'Wheat', [ITEM.CARROT]: 'Carrot',
  [ITEM.POTATO]: 'Potato', [ITEM.BREAD]: 'Bread', [ITEM.CRIMSON_BLOOD]: 'Crimson Blood', [ITEM.CRIMSON_POTION]: 'Healing Potion',
  [ITEM.GLASS_BOTTLE]: 'Glass Bottle', [ITEM.SPEED_POTION]: 'Speed Potion', [ITEM.DIRTY_FLUX]: 'Dirty Flux',
  [ITEM.SLIMEBALL]: 'Slimeball', [ITEM.RAW_CHICKEN]: 'Raw Chicken', [ITEM.COOKED_CHICKEN]: 'Cooked Chicken',
  [ITEM.FEATHER]: 'Feather', [ITEM.EMERALD]: 'Emerald', [ITEM.SAPPHIRE]: 'Sapphire', [ITEM.BACKPACK]: 'Backpack',
  [ITEM.BOW]: 'Bow', [ITEM.ARROW]: 'Arrow', [ITEM.BERRY_RED]: 'Red Berries', [ITEM.BERRY_BLUE]: 'Blue Berries',
  [ITEM.BERRY_YELLOW]: 'Yellow Berries', [ITEM.LEATHER]: 'Leather', [ITEM.PAPER]: 'Paper', [ITEM.BOOK]: 'Book',
  [ITEM.SPELL_CORE]: 'Spell Core',
};

for (const [id, n] of Object.entries(BLOCK_EN)) { if (BLOCKS[id]) BLOCKS[id].nameEn = n; }
for (const [id, n] of Object.entries(ITEM_EN)) { if (ITEMS[id]) ITEMS[id].nameEn = n; }

// Biome (Schlüssel = interne Biom-Keys, siehe BIOME_NAMES in ui.js)
export const BIOME_NAMES_EN = {
  ozean: 'Ocean', see: 'Lake', strand: 'Beach', ebene: 'Plains', wald: 'Forest',
  birkenwald: 'Birch Forest', old_birch: 'Old Birch Forest', tannenwald: 'Spruce Forest',
  spruce_valley: 'Spruce Valley', blumenwiese: 'Flower Meadow',
  sumpf: 'Swamp', wueste: 'Desert', savanne: 'Savanna', badlands: 'Badlands', dschungel: 'Jungle',
  schneelandschaft: 'Snowy Plains', schneewald: 'Snowy Forest', pilzinsel: 'Mushroom Island',
  gebirgsfuss: 'Mountain Foot', haenge: 'Middle Slopes', hochgebirge: 'High Mountains', gipfel: 'Peak',
};
